### ISSUE TITLE
Current per phase?

### ISSUE THREAD

**Issue by ivanlofgren** [fondberg/easee_hass#104]
I assume that all exposed data is added as sensors in the (awesome) integration? Is in that case, the API really not exposing current in, or power in, per phase? Should be requested from Easee since it will be required for correct and efficient power control (eg manual load balancing).

**Comment by tmjo** [comment]
Hi, currents in all phases are available as attributes on the **in_current** sensor, the state is showing the maximum value of the phase currents. Is this what you are looking for?

![image](https://user-images.githubusercontent.com/54450177/109659821-65d1de00-7b68-11eb-80e7-b468322f7e34.png)

**Comment by ivanlofgren** [comment]
Maybe, but in that case the nomenclature is incorrect. It should be L1..L3 (plus possibly N) for incoming currents. T-currents is outgoing currents or even delta connected load currents, which really would mess everything up. I can't believe there are any delta connections in the box though.

Possibly the (T2,T3,T4) is (-L3/2,+L2/2,-L1/2) and T5 is +L3/2, but that would surprise me. T5 could be N-related aswell, but not standard. T1 and T6 is missing. Can't know for sure without more data on internal connections or information on set attribute names. If nothing else, I can measure all currents and do my own analyze, I guess.

Anything you have any data on?

**Comment by olalid** [comment]
Yes, I think the names are confusing, but let me try to explain:

Tx means terminal x in this case. In the unit there are five connection terminals that this refers to.
You can see in the manual from easee what is connected to each terminal depending on your electrical system page 23-24:
https://easee-international.com/uk/wp-content/uploads/2021/02/EN_Easee_HomeCharge_Guide.pdf
They are numbered from the left and 1 is always PE and therefore never have any current (unless there is a fault in the connection).

So it depends on your electrical system which of the Tx values are interesting for you.
In some future we may change this so that it displays more easily understandable names, like L1-L3, but for now we are presenting it as received from easee API.
It is the same with the voltage sensor if you look at the attributes you can see things like "inVoltageT2T3" and this means the voltage as measured between terminal 2 and terminal 3.

outputCurrent is the current limit applied to the charger right now, it is the resulting current limit from all the other current limits, hence "output" current. So it is not a measurement, it is a setting.

There is an ongoing internal discussion how to present the current limits, my personal preference is to collect all current limits in a single sensor with attributes. And change the name of the sensor above to just "current" (i.e. remove the "in_" part of the name).
The current setup is a bit of a result of us having a hard time understanding things initially as well, but I think we are getting more enlightened as we go along, so it should improve as we make future releases.

**Comment by ivanlofgren** [comment]
Ok, thank you Ola! I guess it's natural to call the terminal connections Tn, even though it makes it easy to mix up with the internal three phase lingo. Thank you for the explanation, I can get what I need - closing case. It may, however, be an idea to consider change from Tn to something else in the future to avoid misunderstandings.
