### ISSUE TITLE
Integration fails to start on latest HA core-2021.8.0b4

### ISSUE THREAD

**Issue by henrikeri** [fondberg/easee_hass#125]
The Easee integration fails to start on the latest beta. It fails with the following message:

> Logger: homeassistant.setup

>Source: setup.py:173 
>First occurred: 9:48:42 (1 occurrences) 
>Last logged: 9:48:42

>Setup failed for easee: Unable to import component: cannot import name >'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' >(/usr/src/homeassistant/homeassistant/const.py)

Please let me know if you need more logs or similar.

**Comment by tmjo** [comment]
I get the same error in my dev container. Seems to be related to a renaming of constants in HA, probably due to some clean-up for the new energy feature. See [here](https://github.com/home-assistant/core/commit/074d762664976d3414b8a33535e9b850d80a42fa#diff-07e20eb7c6560330f9774eb23343f5dd3002106bb8b6523ccb18d95857990d77) where VOLT is renamed to ELECTRIC_POTENTIAL_VOLT and ELECTRICAL_CURRENT_AMPERE is renamed to ELECTRIC_CURRENT_AMPERE.

We'll fix this as soon as possible.

**Comment by henrikeri** [comment]
I forked and created PR #126 to close this.
