### ISSUE TITLE
Use the EV charger data into the new energy feature

### ISSUE THREAD

**Issue by rhoddan** [fondberg/easee_hass#130]
Maybe it’s already possible (but I haven’t found how) - Use data from this integration to feed the new energy module? I can’t find that entity in the configuration of energy module.

**Comment by astrandb** [comment]
Support for Energy panel and long term statistics will be added. No planned delivery date though 🙃

**Comment by rhoddan** [comment]
Not sure that I have did it correctly but the consumption seems to be very high with data source from equalizer?

![Screenshot 2021-08-13 084732](https://user-images.githubusercontent.com/33499995/129316347-6d0463c4-8851-4276-b1d7-2f1e58c067db.png)

**Comment by olalid** [comment]
This is possibly the same issue as seen by some users where the energy meter is displayed as 10 times higher than the meter actually displays. It is likely due to an imcompatibility issue between the meter and equalizer. Easee are aware of the problem and will fix it eventually. A workaround in the meantime a template sensor could be used to divide the value by 10.

**Comment by olalid** [comment]
I am closing this as this bug is in the equalizer and not in the HA component.
