### ISSUE TITLE
Was does waiting_in_fully mean?

### ISSUE THREAD

**Issue by andig** [fondberg/easee_hass#169]
I hope the question is not too OT. I'm working on https://github.com/evcc-io/evcc/issues/2519 and stumbled across this repo. Has anyone seen `waiting_in_fully` after switching from 3p to 3p at circuit level and knows why charging doesn't start again?

**Comment by olalid** [comment]
Seems like an interesting project.

Not sure what you mean by switching from 3p to 3p though, was that a typo?
I can not recall seeing that specific message anyway.

My german is not so good unfortunately, but I got the impression that you are using a mix of calls to resume/pause and setting the dynamic circuit current to different values.
This seems to me like something a bit unnecessary, it should perhaps not be a problem, but you never know.
Since setting the dynamic circuit current to less than 6A on all phases will cause the charging to pause until the limit is raised to 6A or above again the pause/resume APIs are kind of redundant when you are working on this kind of load balancing.
And setting 2 of the phases to 0 while setting 1 phase to something above 6A means the charger will use only that phase, you do not have to do anything else than this to make it switch between modes, it will pause/resume automatically and change mode as required without any need to call any other API.
But maybe I am saying obvious things you already know...

**Comment by andig** [comment]
> Seems like an interesting project.

Thank you very much! The docs are in German, but the application is in english as well- happy to answer any questions you may have.

> Not sure what you mean by switching from 3p to 3p though, was that a typo? I can not recall seeing that specific message anyway.

Sorry, I meant 3p -> 1p

> My german is not so good unfortunately, but I got the impression that you are using a mix of calls to resume/pause and setting the dynamic circuit current to different values. This seems to me like something a bit unnecessary, it should perhaps not be a problem, but you never know. Since setting the dynamic circuit current to less than 6A on all phases will cause the charging to pause until the limit is raised to 6A or above again the pause/resume APIs are kind of redundant when you are working on this kind of load balancing. And setting 2 of the phases to 0 while setting 1 phase to something above 6A means the charger will use only that phase, 

Yes, that's the 1p charging I want to have.

> you do not have to do anything else than this to make it switch between modes, it will pause/resume automatically and change mode as required without any need to call any other API. But maybe I am saying obvious things you already know...

I didn't know that. However- as the calling code is generic for different kinds of chargers- I'll leave as-is for the time being. It shouldn't matter really or maybe just take a little longer.

It seems that `waiting_in_fully` indicates that the car is connected but doesn't charge although power is available. We'll yet have to find out why that would happen. Thanks for the quick response!
