### ISSUE TITLE
Charging cost

### ISSUE THREAD

**Issue by stigvi** [fondberg/easee_hass#215]
### Feature request

I use the service call each hour to set charging cost. That makes it possible to see charging cost pr day, month and year in the Easee app.

Is this information available in the API? And in that case, could it be read by this integration?

### What version of the integration are you using?

v0.9.45

**Comment by tmjo** [comment]
Seems like it is available in the API, so this is probably something we could easily implement. I don't think it was there in the past, but now I see calls for weekly, monthly, yearly and custom periods of cost. Never tried it, but I guess it works like we can imagine. 

See for instance [here](https://developer.easee.cloud/reference/get_api-sites-siteid-breakdown-from-to), and it is available for testing on that site as well if you wanna give it a spin.

**Comment by AMajland** [comment]
Many already pay for their electricity with a rate that changes every hour - and many more will probably go that way in the future. Besides the cost of the electricity the transport is not fixed anymore in Denmark Either. Lastly the first electricity company has now annonced that their profit on top of the spot price will also wary by the over. So Easee simple cost calculaion wont cut it for many anyway ...

To get  the real charging cost gets complicated real fast since it is a combination of multiple factors. 

Right now i'm considering to try to do it based on the Easee's Lifetime energy. That is every hour calculate the cost of the charging the previous hour.
(Spotprice* + local transport* + profit* + regional trransport + state taxes ) * VAT (Where * are all variable)

**Comment by olalid** [comment]
Can someone confirm that the easee cloud actually keeps track of the cost over time? I was under the impression that the cost set is just used to do a simple multiplication of kWh  *  cost. Which means also historical cost will change when you change the cost?
I mean, if we implement this, I do not want people to have the wrong expectations.

**Comment by stigvi** [comment]
> Many already pay for their electricity with a rate that changes every hour - and many more will probably go that way in the future. Besides the cost of the electricity the transport is not fixed anymore in Denmark Either. Lastly the first electricity company has now annonced that their profit on top of the spot price will also wary by the over. So Easee simple cost calculaion wont cut it for many anyway ...
> 
> To get the real charging cost gets complicated real fast since it is a combination of multiple factors.
> 
> Right now i'm considering to try to do it based on the Easee's Lifetime energy. That is every hour calculate the cost of the charging the previous hour. (Spotprice* + local transport* + profit* + regional trransport + state taxes ) * VAT (Where * are all variable) The image is just the spot price ![image](https://user-images.githubusercontent.com/97510471/193423390-c4067eb4-2ecc-408f-b18c-f4c437853ddd.png)
> 
> From 17-20 the local transport is 0,9734kr/kWh and 0,3875 kr/kWh otherwise
> 
> So the evening peak gets real expensive and tomorrow peaks is ¨4,25kr/kWh or ~0,57€/kWh

I am using the service easee.set_charging_cost to set the charging cost. I do this every hour when the cost is changing. So **my app** is showing me prices based on the charging cost **I have provided**. I dont know anything about Easee's simple cost calculation, but I suppose they have put enough brain power into this so that the cost provided in the app is accurate.

**Comment by stigvi** [comment]
> Can someone confirm that the easee cloud actually keeps track of the cost over time? I was under the impression that the cost set is just used to do a simple multiplication of kWh * cost. Which means also historical cost will change when you change the cost? I mean, if we implement this, I do not want people to have the wrong expectations.

I have not looked at the api and what is provided there, but here is 4 screenshots from the app. In 2 of the screenshots, you can see that they use 2 different prices for kwh/h and these 2 are provided by me with the service call easee.set_charging_cost

![Screenshot_20221002-124651](https://user-images.githubusercontent.com/25978315/193450919-b45c6709-ab2b-443e-a469-27026b1a5819.png)
![Screenshot_20221002-124539](https://user-images.githubusercontent.com/25978315/193450920-ca6dab32-7b31-46f1-8e6d-856883cdb9b1.png)
![Screenshot_20221002-124556](https://user-images.githubusercontent.com/25978315/193450922-a0d8e050-0b55-49fc-bc68-ba69e85408cd.png)
![Screenshot_20221002-124629](https://user-images.githubusercontent.com/25978315/193450923-fc4d2b4d-a9a0-47e0-8857-a4529db14bc2.png)

**Comment by olalid** [comment]
Yes, that looks promising.
So 3 sensors?
One that shows the cost since the start of the current year?
One that shows the cost since the start of the current month?
One that shows the cost since the start of the current day?
Since these require polling we need to figure out when we should do that.
Obviously we need to poll at startup, but after that perhaps only when lifetime_energy changes or when a new day starts (+ some random offset to not stress servers unnecessarily).

**Comment by PalleRaa** [comment]
> I am using the service easee.set_charging_cost to set the charging cost. I do this every hour when the cost is changing.

@stigvi This seems like good to way to do it. I have a entity with the current price that is always up to date. How do I push that value to the set_charging_cost in HA?
