### ISSUE TITLE
Charger Is_enabled is  randomly set to off by supervisor

### ISSUE THREAD

**Issue by BGunnarB** [fondberg/easee_hass#270]
### Question

I have installed the easee integration. Equipment is the easee charger and the easee load balancer.
When the integration is enabled, at intervals between minutes and up to an hour, the charger **is_enabled** is set to off by the Supervisor. I can enable the charger manually through the UI but the Supervisor sets **is_enabled** to off after some time.

I cannot find any further information in the logs but tomorrow I will enable more detailed logging.

How should I trace the source of this action by the Supervisor? I do not have any automations active for the charger.

HA version is 9.5

### What version of the integration are you using?

0.9.48

**Comment by olalid** [comment]
Is your charger controller by some 3rd party, like Tibber perhaps? Is that what you mean when you say "supervisor"?

PS. There has never been a version of HA with version number 9.5, you must mean something else...?

**Comment by BGunnarB** [comment]
Hi!
Returning with some more info.
Configuration:
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend-version: 20230110.0 - latest

No third party controller like Tibber, only the easee load balancer connected to the same network.
Below is the output from the log in the integration when I manually activated the charger at 17.08.08
Something then deactivates it at 17.11.37
This is the output from the log during the same period:

```
2023-01-31 17:08:07.841 DEBUG (MainThread) [pyeasee.easee] POST: /api/chargers/EH2ZYVH2/settings ({'json': {'enabled': True}})
2023-01-31 17:08:07.841 DEBUG (MainThread) [pyeasee.easee] verify_updated_token: 2023-02-01 16:47:53.499127, 2023-01-31 17:08:07.841223, False

2023-01-31 17:11:37.509 DEBUG (MainThread) [pyeasee.easee] POST: /api/chargers/EH2ZYVH2/settings ({'json': {'enabled': False}})
2023-01-31 17:11:37.509 DEBUG (MainThread) [pyeasee.easee] verify_updated_token: 2023-02-01 16:47:53.499127, 2023-01-31 17:11:37.509285, False
```
![Screenshot 2023-01-31 at 17 12 02](https://user-images.githubusercontent.com/11635518/215820892-5d1eb3a9-6987-4068-88b8-5d1750a80323.png)

What is causing the charger to go inactive?

**Comment by astrandb** [comment]
Log book entries by Supervisor can difficult to track down. They can be caused by an add-on e.g Node Red, or custom voice assistants etc.

**Comment by olalid** [comment]
It must be something you have installed/configured that is calling the switch.turn_on/turn_off service.
Maybe it is something that is supposed to turn off/on something entirely different but accidentally was configured to use the is_enabled switch of the easee integration instead of the switch for a lamp or whatever...
Perhaps you can disable addons/automations one by one and eventually figure out what is going on.
Or perhaps if you look at the rows above the log entries you pasted above you can get some kind of hint of what is calling the turn_on/off service, but that is just speculation.

This is in any case nothing we diagnose from within the Easee integration since this is a problem that is clearly outside this component.
I suggest you try to get help in a more general place, like the home assistant forum or some home assistant facebook group.

**Comment by BGunnarB** [comment]
OK, so back to square one then.
But at least I now know where not to look. That is always useful.
Thanks for rapid answers and your support!

**Comment by olalid** [comment]
Ok, good luck.
