### ISSUE TITLE
Rate throttling by ease

### ISSUE THREAD

**Issue by nosuntoday** [fondberg/easee_hass#281]
### The problem

I am using your add-on and evcc (evcc.io) and easee is restricting access to the API with rate throttling. It might be a good idea to include the possibility in your add-on to limit access to the API, e.g. very 20 seconds. It is said that easee is fine with every 10 seconds but this applies to access from the same IP-address (and I have two chargers ...).

At the moment I ran into problems in a regular basis ... e.g.

Get "https://api.easee.cloud/api/chargers/EH####/site"
net/http: request canceled (Client.Timeout exceeded while awaiting headers) 

Oliver

### Version of Easee integration having the issue?

all

### Version of Home Assistant Core having the issue?

all

**Comment by olalid** [comment]
Let me start out by saying, this integration typically does not poll.
We use a SignalR connection to the server on which new states are pushed out.

With the exception of polling for schedules and cost sensors, which only happens when we have a reason to think it has changed (i.e. when a related change is pusfed out over the SignalR connection or after midnight).

In any case, the API you mention is not polled on a regular basis, but only once at startup.
If you have more than one site (that you have selected to monitor in the integration settings) it would poll that API once for each site. Do you have more than one site, and does that cause this issue for you?

If you enable debug logging for the Easee component, can you see anything more useful when you have issues?
(i.e. add this to your configuration.yaml):

```
logger:
  default: info
  logs:
    pyeasee: debug
    custom_components.easee: debug
```

Rate limiting in connection with EVCC has been discussed before also, see https://github.com/fondberg/easee_hass/issues/263
At that point in time we could not really figure out what we should change to make it better, since as I said, we are not polling...

**Comment by olalid** [comment]
Closing this since this is most likely a problem with evcc.io implementation.
