### ISSUE TITLE
Is it possible to change phase mode from Home Assistant?

### ISSUE THREAD

**Issue by uphillbattle** [fondberg/easee_hass#337]
### Question

My charger is connected to all three phases in a TN network. I normally use three-phase charging during winter time.

Grid tariffs in Norway depend on the average of the three highest, daily one-hour consumptions in kWh. Most grid companies set these limits at 2, 5, 10, … kWh/h. During winter, the consumption for heating the house makes it generally very hard, if at all possible, to stay below 5 kWh/h, but during the warmest summer months, <5 kWh/h is possible. 

I control the Easee charger to limit the overall consumption (for the house) to stay below 10 kWh/h in the winter and 5 kWh/h in the summer. However, achieving 5 kWh/h in the summer proves to be difficult because the minimum charging power for three-phase TN is about 4 kW (6 A * 230 V * 3 = 4140 W). I could change the phase mode to 1-phase manually for the summer months, but I would rather automate it…

Is it possible to change the phase mode - from three-phase/auto to one-phase - from HA? If not, is this a feature that can be implemented?

### What version of the integration are you using?

0.9.54

**Comment by olalid** [comment]
The integration can not change the currently change the mode setting you are talking about. I think it is possible to implement though, but not sure if is really needed to accomplish what you want to do.

I say that because if you set the charger to automatic mode, you can control if the charger uses 1 or 3 phase mode by setting the limits accordingly.
E.g. you can call the set_circuit_dynamic_limit service and set the arguments P1 to 10, P2 to 0 and P3 to 0. It will then switch to charging with phase 1 only (limited to 10A).
With reservation for that it might work differently in Norwegian IT networks...

**Comment by uphillbattle** [comment]
Ah, yes, of course, that should do the trick. Will try that. Thanks.
