### ISSUE TITLE
Request Development Admin User credentials 

### ISSUE THREAD

**Issue by KIDNORswe** [fondberg/easee_hass#365]
### Feature request

**Is there a possibility to wish for a change to how this integration is handling username, password and ID please?** The only way to change a password seem to be; uninstalling and setting it up again. Or enter the .storage directory. Not ideal and creates a problem... its a pain in the **s. 

First step, an option via  “configuration” to update any of the user account details for the function would be a big improvment. Even better, give us the option to use helpers (input helpers) to integrate into a frontend UI admin site.

I would love to contribute myself but unfortunately don’t know how. Don’t know Python… so am a bit useless. 

BIG shout out and THANK YOU to the one creating this integration + all others who have contributed to make it even better.

### What version of the integration are you using?

v0.9.47

**Comment by olalid** [comment]
I think we are handling password/username like most (or all?) other integrations are?
I.e. you are asked for username/password when you add the integration. 
And if you need to change it you remove the integration and add it again, which is usually a quick process.
This is the "HA way" to handle usernames/passwords in integrations as far as I have seen.
In my system I have 3 other integrations with username/password that works the same way, and none that works in a different way.

What is your use-case, why do you need to change the username/password often? Not sure what you mean by ID?

**Comment by astrandb** [comment]
As @olalid mentioned above we have followed the "standard" in Home Assistant. If you have issues with this standard you should aim your complaints towards Home Assistant.

It is technically possible to force a reauthentication flow in this integration if the Easee API sends a specific status code when a request fails due to authentication error (e.g. changed password in Easee cloud services). Some research and testing is needed to ensure that trapping this error is not causing more trouble than needed. There are examples from other integrations where the API can respond with authentication errors now and then and a simple automatic retry is sufficient to recover. If we trap such errors and force a manual intervention we will most certainly get more complaints.

However, we would still need to make a remove/install if the new authentication also includes changes in access rules (e.g. a change between admin and user privileges) in the Easee Cloud. Otherwise there will be dead sensors etc hanging in the integration. There is no practical way to handle this situation except to remove and reinstall the integration.

**Comment by KIDNORswe** [comment]
**@olalid** Hi, sorry, I don't want you to see this as a criticism directed to you as developer or collaborator. The criticism is directed to the way HA is structured and handles user credentials. Is a shame this integration don't have a better solution as it is a very useful one. I wish there was a guide and common solution on how credentials should be handled in HA. 

Other integrations have been proactive and created a better solution. As "norrvana31" is commenting; "You don't need to un-install an app on your smartphone/iPad or PC when changing a password."

- HomeAssistant - Tapo: Camera Control : let you change and update configuration and settings giving you options to change IP address, username, password and more. Good example on how it should be (my opinion).

-  tuya-local (https://github.com/make-all/tuya-local): lets you update and change the "Local key' and IP. Local key being similar to a username but the units identification key connected via the cloud.

> What is your use-case, why do you need to change the username/password often? Not sure what you mean by ID?

A username isn't changed often but is a part of the user credentials.. A password could and maybe should be changed at least twice a year. I wish the process was easier and quicker. For my dad who loves that setup with car charger implemented into HA to use less apps, everything in one app... does not know or have the knowledge on how to uninstall and add again. Would be less work for me + the integration would appear much better if this could be an option.

At last, sorry but I was only asking if its possible for an enhancement. Its a very good integration and everything is working great except from this. I'll ask a friend instead if we can build or own integration with a better solution. So.. case closed.
